'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class MenuContrato

    '''<summary>
    '''LabelMensaje control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LabelMensaje As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''FormViewMenuContrato control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FormViewMenuContrato As Global.System.Web.UI.WebControls.FormView

    '''<summary>
    '''SqlDataSourceMenuContrato control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlDataSourceMenuContrato As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''SqlDataSourceClienteContrato control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlDataSourceClienteContrato As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''SqlDataSourceGuardaClienteContrato control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlDataSourceGuardaClienteContrato As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''SqlDataSourceEstadoContrato control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlDataSourceEstadoContrato As Global.System.Web.UI.WebControls.SqlDataSource
End Class
